### ISSUE TITLE
AttributeError: Marker name must NOT start with underscore

### ISSUE THREAD

**Issue by jayvdb** [rciorba/pytest-fixture-marker#2]
First time running with this plugin, so could be lots of causes, but when running pytest 5.4.3 in xdoctest project, I get

```py
...
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pytest_fixture_marker.py", line 19, in pytest_collection_modifyitems
INTERNALERROR>     item.add_marker(expression.format(fixture))
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/_pytest/nodes.py", line 254, in add_marker
INTERNALERROR>     marker_ = getattr(MARK_GEN, marker)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/_pytest/mark/structures.py", line 318, in __getattr__
INTERNALERROR>     raise AttributeError("Marker name must NOT start with underscore")
INTERNALERROR> AttributeError: Marker name must NOT start with underscore
```

**Comment by rciorba** [comment]
Thanks for submitting the issue!

You can work-around by passing a custom `--fixture-marker-expression=fixture_{}`

The default `{}_fixture` sadly breaks if the fixture name starts with an underscore.
I'll change the default for a new release.

**Comment by jayvdb** [comment]
Thanks.  I've lost track of where I was using xdoctest, but I'll keep this in mind when I need it again.
